name: Deploy Terraform to HCP

on:
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/deployment.yml'

env:
  AWS_REGION: 'us-east-2'
  HCP_TERRAFORM_ORG: enpicie
  HCP_TERRAFORM_WORKSPACE: hcp-tf-aws-lambda-apigw-role
  HCP_TERRAFORM_PROJECT_ID: prj-pAh9kkvyHMNEjs4z

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup HCP Terraform Workspace
        id: setup_workspace
        uses: chzylee/action-workflow-hcp-terraform-workspace-setup@v1.0.0
        with:
          tfc_organization: ${{ env.HCP_TERRAFORM_ORG }}
          tfc_workspace: ${{ env.HCP_TERRAFORM_WORKSPACE }}
          tfc_project_id: ${{ env.HCP_TERRAFORM_PROJECT_ID }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}

      - name: Attach IAM Permission Variable Set to this Workspace
        uses: chzylee/action-workflow-hcp-terraform-var-set-attach@v0.1.9
        with:
          tfc_organization: ${{ env.HCP_TERRAFORM_ORG }}
          tfc_workspace_id: ${{ steps.setup_workspace.outputs.workspace_id }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}
          var_set_name: ${{ vars.HCP_TF_ROLE_IAM_PERMS_VAR_SET_NAME}}

      - name: Deploy Config via HCP Terraform
        uses: chzylee/action-workflow-hcp-terraform-run@v1.1.1
        with:
          terraform_directory: ./ # Action run from context of the repository root
          tfc_organization: ${{ env.HCP_TERRAFORM_ORG }}
          tfc_workspace: ${{ env.HCP_TERRAFORM_WORKSPACE }}
          tfc_token: ${{ secrets.TF_API_TOKEN }}

      - name: Push Org Variable for Variable Set to Owning Org
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }} # Token with admin:org
          VAR_NAME: HCP_TF_ROLE_LAMBDA_APIGW_PERMS_VAR_SET_NAME
          VAR_VALUE: 'AWS HCP TF OIDC Role - Lambda+APIGateway Perms'
          ORG_NAME: ${{ github.repository_owner }}
        run: |
          echo "Setting org-level variable '$VAR_NAME' in org '$ORG_NAME'..."
          gh variable set "$VAR_NAME" \
            --org "$ORG_NAME" \
            --body "$VAR_VALUE" \
            --visibility all
